Repository pagopa/io-services-metadata, pull requests merged in 2024-10, with the labels that each got.

#844 [IOCOM-1757] addition of `landing_banners` field for multi-banner handling in app IO
  definitions.yml
  status/backend.json
Labels: IO-Comunicazione

#853 feat: [PE-754]: CGN activation screen images
  bonus/bonus_available_v2.json
  bonus/cgn/logo/CGN_Chi può attivarla.png
  bonus/cgn/logo/CGN_Come si usa.png
  bonus/cgn/logo/CGN_Facile da attivare.png
Labels: enhancement

#847 [IOPID-2359] delete remote session refresh FF
  definitions.yml
  package.json
  status/backend.json
Labels: A&I
