Repository pagopa/io-services-metadata, pull requests merged in 2024-07, with the labels that each got.

#794 `fims.historyEnabled` flag in definitions.yml
  definitions.yml
Labels: IO-Comunicazione

#802 chore: disable new wallet section payment feature flag
  status/backend.json
Labels: dont-merge ✋

#815 [IOPID-2049] Add remote FF of sessionRefresh after two minutes in background
  definitions.yml
  package.json
  status/backend.json
Labels: A&I
