Repository pagopa/io-services-metadata, pull requests merged in 2025-07, with the labels that each got.

#1005 chore: Disable WebView payment flow on iOS
  status/backend.json
Labels: scheduled-merge 🕒, B&P

#1006 feat: [IOCOM-2458] SEND AAR QRcode Regex
  definitions.yml
  status/backend.json
Labels: IO-Comunicazione

#1009 chore: [IOBP-1809] Enable payments maintenance banner
  status/backend.json
Labels: scheduled-merge 🕒, B&P

#1012 chore: [IOBP-1874] Add banner status message `label_cta` property
  definitions.yml
  package.json
Labels: enhancement
