Repository pagopa/io-services-metadata, pull requests merged in 2025-06, with the labels that each got.

#977 chore: Disable WebView payment flow
  status/backend.json
Labels: B&P

#979 chore: Enable webview payment flow on version `3.6.0.9`
  status/backend.json
Labels: scheduled-merge 🕒

#982 chore: Disable webview payment flow
  status/backend.json
Labels: scheduled-merge 🕒

#983 chore: Enable payment webview flow
  status/backend.json
Labels: scheduled-merge 🕒

#984 chore: Disable WebView payment flow
  status/backend.json
Labels: scheduled-merge 🕒

#985 chore: Enable payment webview flow
  status/backend.json
Labels: scheduled-merge 🕒

#986 chore: Disable WebView payment flow
  status/backend.json
Labels: scheduled-merge 🕒

#992 chore: [IOBP-1749] Add cdc hero image
  bonus/cdc/logo/hero-cdc.png
Labels: B&P

#991 chore: [IOBP-1747] Add FIMS `iOSCookieDisabledServiceIds ` property to disable cookie sharing on iOS
  definitions.yml
  package.json
  status/backend.json
Labels: IO-Comunicazione

#993 chore: Enable payment webview flow
  status/backend.json
Labels: scheduled-merge 🕒

#994 chore: Disable WebView payment flow
  status/backend.json
Labels: scheduled-merge 🕒
