Repository pagopa/io-services-metadata, pull requests merged in 2025-09, with the labels that each got.

#1020 Revert "chore: [IOPID-3364] add maintenance banner on landing and email verification screens "
  status/backend.json
Labels: A&I

#1023 [IOCOM-2575] SEND AAR QR CODE regex update
  status/backend.json
Labels: IO-Comunicazione

#995 chore: [IOBP-1756] Align tos and onboarding text
  bonus/bonus_available_v2.json
Labels: B&P

#1025 refactor: [IOPID-2649] Remove cieid ff occurrences from `definitions.yml` and form `backend.json`
  definitions.yml
  status/backend.json
Labels: A&I

#1028 chore: [IOBP-000] Restore IDPay Bonus ff
  status/backend.json
Labels: B&P

#1029 feat: [IOCOM-2554] Added Send AAR delegate url
  definitions.yml
  status/backend.json
Labels: IO-Comunicazione

#1032 chore: [IOBP-2032, IOBP-1925] CdC FAQ
  bonus/bonus_available_v2.json
  contextualhelp/data.json
Labels: B&P

#1034 refactor: [IOBP-000] Update CdC TOS copy
  bonus/bonus_available_v2.json
Labels: B&P
