Repository pagopa/io-services-metadata, pull requests merged in 2025-02, with the labels that each got.

#931 Added new method Satispay on FAQ PAYMENTS_HOME
  contextualhelp/data.json
Labels: scheduled-merge 🕒, B&P

#933 [IOPID-2684] Bump `min_app_version` from `2.78.0.11` to `2.81.0.8`
  status/versionInfo.json
Labels: scheduled-merge 🕒

#934 [IOPID-2670] edit remote URL that refers to ioapp.it with account.ioapp.it
  contextualhelp/data.json
  status/backend.json
Labels: scheduled-merge 🕒

#928 [IOPLT-927] Adds the remote config for app review feature
  definitions.yml
  status/backend.json
Labels: dont-merge ✋

#935 chore: [IOBP-1180] Disable IDPay feature
  status/backend.json
Labels: B&P

#936 [IOPID-2721] FAQ Banner educational for Zendesk subcategories
  assistanceTools/zendesk.json
  definitions.yml
Labels: A&I

#937 [IOPID-2718] FastLogin expiration threshold configuration
  definitions.yml
  status/backend.json
Labels: A&I

#938 [IOPID-2756] Change Banners priority order
  status/backend.json
Labels: A&I

#939 chore: [IOCOM-2100] FIMS configuration list
  definitions.yml
  status/backend.json
Labels: IO-Comunicazione

#943 [IOCOM-2206] addition of PN notification service ID to backend.json
  definitions.yml
  status/backend.json
Labels: IO-Comunicazione
