Repository pagopa/io-services-metadata, pull requests merged in 2025-01, with the labels that each got.

#919 [SIW-1953] Add iPatente CTA property in ItwConfig
  definitions.yml
  package.json
  status/backend.json
Labels: dont-merge ✋

#923 [SIW-1953] Add iPatente CTA property in ItwConfig
  definitions.yml
  package.json
  status/backend.json
Labels: dont-merge ✋

#924 [PE-863] Enable CGN short maintenance banner warning
  status/backend.json
Labels: scheduled-merge 🕒, B&P

#927 chore: [PE-863] Removed CGN status banner
  status/backend.json
Labels: B&P

#929 [IOCOM-2071] Flag for disabling IOMarkdown remotely
  definitions.yml
  status/backend.json
Labels: IO-Comunicazione
