Repository pagopa/io-services-metadata, pull requests merged in 2025-08, with the labels that each got.

#1013 feat: [IOCOM-2517] Update SEND AAR QRCode regex
  status/backend.json
Labels: IO-Comunicazione

#1015 chore: [IOBP-1926] Add `show_cgn_categories_modal` FF
  definitions.yml
  package.json
  status/backend.json
Labels: B&P

#1014 chore: [IOBP-1930] Enable CGN status banner short maintenance
  status/backend.json
Labels: scheduled-merge 🕒, B&P

#1017 chore: Disable CGN maintenance banner
  status/backend.json
Labels: B&P
